base/urls.py
#!/usr/bin/python
# coding: utf-8

from django.conf.urls import url
from django.conf import settings
from django.contrib.auth.views import login, logout

from . import views

urlpatterns = [
    url(r'^$', views.home, name='index'),
    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'logout.html'}, name='logout'),

]

urlpatterns += [url(r'^{}/$'.format(name), views.static_site(file), name=name)
                for name, file in settings.STATIC_SITES.items()]

management/urls.py
#!/usr/bin/python
# coding: utf-8
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.manage, name='management'),
    url(r'^add/$', views.add, name='add'),
    url(r'^edit/(?P<id>\d+)/$', views.edit, name='edit'),
    url(r'^remove/(?P<id>\d+)/$', views.remove, name='remove'),
    url(r'^upload_title_page/(?P<id>\d+)/$', views.upload_title_page, name='upload_title_page')
]

old_prints/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from prints import views as prints

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('base.urls')),
    url(r'^prints/', include('prints.urls', namespace='prints')),
    url(r'^manage/', include('management.urls', namespace='management')),
    url(r'^api/v1/prints/(?P<page>\d+)/$', prints.filter, name='filter'),
    url(r'^api/v1/name_index/(?P<page>\d+)/$', prints.name_index, name='name_index'),
]

prints/urls.py
#!/usr/bin/python
# coding: utf-8


from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.search, name='search'),
    url(r'^collection/$', views.collection, name='collection'),
    url(r'^by_name/$', views.by_name, name='by_name'),
    url(r'^single/(?P<id>\d+)/$', views.single, name="single"),
    url(r'^view/(?P<id>\d+)/$', views.view, name="view"),
]

base/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'search.html')


def static_site(template_name):
    return lambda request: render(request, template_name)

base/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}Starodruki{% endblock %}</title>
    <meta name="description" content="Strona ze starodrukami">
    <meta name="author" content="Piotr Wójcik">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">  <!-- Google web font "Open Sans" -->
    <link rel="stylesheet" href="{% static "/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "/css/style.css" %}">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block extra_head %}{% endblock %}
</head>
<body>

{% block menu %}{% include "menu.html" %}{% endblock %}

<div class="container-fluid main-container">
{% block content %}{% endblock %}
</div>

{% block footer %}{% include "footer.html" %}{% endblock %}


{% block script %}

<script src="{% static "/js/jquery-1.11.3.min.js" %}"></script>
<script src="https://www.atlasestateagents.co.uk/javascript/tether.min.js"></script>
<script src="{% static "/js/bootstrap.min.js" %}"></script>

{% block extra_script %}{% endblock %}

{% endblock %}
</body>
</html>

base/templates/footer.html
<footer class="classic-footer">
    <div class="container-fluid">
        <!--<div class="row">-->

            <!--<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">-->

                <!--<div class="footer-content-box">-->
                    <!--<h3 class="brown-text t-title footer-content-box-title">Proin eu posuere felis</h3>-->
                    <!--<div class="gray-bg">-->
                        <!--<p>Classic is free HTML CSS website template provided by templatemo for everyone. Feel free to use it.</p>-->
                        <!--<p>Aenean cursus tellus mauris, quis consequat mauris dapibus id. Donec scelerisque porttitor pharetra.</p>-->
                        <!--<p><strong>Danny Egg (Executive)</strong></p>-->
                    <!--</div>-->
                <!--</div>-->

            <!--</div>-->

            <!--<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">-->
                <!--<div class="footer-content-box footer-links-container">-->

                    <!--<h3 class="brown-text t-title footer-content-box-title">Nulla tortor dolor</h3>-->
                    <!--<nav>-->
                        <!--<ul class="nav">-->
                            <!--<li><a href="#" class="footer-link">Tincidunt non faucibus</a></li>-->
                            <!--<li><a href="#" class="footer-link">Vestibulum tempor</a></li>-->
                            <!--<li><a href="#" class="footer-link">Fusce non turpis euismod</a></li>-->
                            <!--<li><a href="#" class="footer-link">Lorem ipsum dolor sit</a></li>-->
                            <!--<li><a href="#" class="footer-link">Nam in augue consectetur</a></li>-->
                            <!--<li><a href="#" class="footer-link">Text Link Color #CCCC66</a></li>-->
                        <!--</ul>-->
                    <!--</nav>-->

                <!--</div>-->

            <!--</div>-->

            <!--&lt;!&ndash; Add the extra clearfix for only the required viewport-->
                <!--http://stackoverflow.com/questions/24590222/bootstrap-3-grid-with-different-height-in-each-item-is-it-solvable-using-only-->
            <!--&ndash;&gt;-->
            <!--<div class="clearfix hidden-lg-up"></div>-->

            <!--<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">-->

                <!--<div class="footer-content-box">-->

                    <!--<h3 class="brown-text t-title footer-content-box-title">Etiam mollis ornare</h3>-->
                    <!--<p class="margin-b-30">Aenean cursus tellus mauris, quis consequat mauris dapibus id. Donec scelerisque porttitor pharetra.</p><hr class="tm-margin-b-30">-->
                    <!--<p class="margin-b-30">Aenean cursus tellus mauris, quis consequat mauris dapibus id. Donec scelerisque porttitor pharetra.</p><hr class="tm-margin-b-30">-->
                    <!--<p class="margin-b-30">Aenean cursus tellus mauris, quis consequat mauris dapibus id. Donec scelerisque porttitor pharetra.</p>-->
                    <!--<a href="#" class="brown-btn gray-btn text-uppercase">Read More</a>-->

                <!--</div>-->

            <!--</div>-->

            <!--<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">-->

                <!--<div class="footer-content-box">-->

                    <!--<h3 class="brown-text t-title footer-content-box-title">Fusce non turpis</h3>-->
                    <!--<div class="margin-b-30">-->
                        <!--<img src="img/tm-img-100x100-1.jpg" alt="Image" class="footer-thumbnail">-->
                        <!--<img src="img/tm-img-100x100-2.jpg" alt="Image" class="footer-thumbnail">-->
                        <!--<img src="img/tm-img-100x100-3.jpg" alt="Image" class="footer-thumbnail">-->
                        <!--<img src="img/tm-img-100x100-4.jpg" alt="Image" class="footer-thumbnail">-->
                        <!--<img src="img/tm-img-100x100-5.jpg" alt="Image" class="footer-thumbnail">-->
                        <!--<img src="img/tm-img-100x100-6.jpg" alt="Image" class="footer-thumbnail">-->
                    <!--</div>-->
                    <!--<p class="margin-b-20">Curabitur dui massa, aliquam quis mi sed, tempor vulputate tellus. Sed vestibulum non neque.</p>-->
                    <!--<a href="#" class="brown-btn gray-btn text-uppercase">Browse</a>-->

                <!--</div>-->

            <!--</div>-->


        <!--</div>-->

        <div class="row">
            <div class="col-xs-12 copyright-col">
                <p class="copyright-text">Copyright 2016 meteran</p>
            </div>
        </div>
    </div>
</footer>

base/templates/index.html
{% extends "base.html" %}
{% block title %}info - starodruki{% endblock %}


{% block content %}
<div class="row search-section">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
        <form action="/" method="post" class="default-form">
            <div class="input-group">
                <input type="text" id="search" name="search" class="form-control search-form-control" placeholder="Szukaj"/>
                <span class="input-group-btn">
                    <button type="submit" class="btn brown-btn">Szukaj</button>
                </span>
            </div>
        </form>
    </div>
    <div class="col-lg-2"></div>
</div>

{% endblock %}

base/templates/login.html
{% extends "base.html" %}


{% block content %}
<div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
        <form class="login" method="POST" action="/login/">
            {% csrf_token %}

            {{form.as_p}}

            <button type="submit">Zaloguj</button>
        </form>
    </div>
    <div class="col-lg-2"></div>
</div>

{% endblock %}

base/templates/logout.html
{% extends "base.html" %}


{% block content %}
<div class="row">
    <div class="col logout">
        <h1>Wylogowałeś się</h1>
    </div>
</div>

{% endblock %}

base/templates/menu.html
<div class="header">
    <div class="container-fluid">
        <div class="header-inner">
            <a href="/" class="navbar-brand site-name">Starodruki</a>

            <!-- navbar -->
            <nav class="navbar main-nav">

                <button class="navbar-toggler hidden-md-up" type="button" data-toggle="collapse" data-target="#navbar">
                    &#9776;
                </button>

                <div class="collapse navbar-toggleable-sm" id="navbar">
                    <ul class="nav navbar-nav">
                        <li class="nav-item{% if request.resolver_match.url_name == "collection" %} active{% endif %}">
                            <a href="{% url "prints:collection" %}" class="nav-link">Przeglądaj</a>
                        </li>
                        <li class="nav-item{% if request.resolver_match.url_name == "by_name" %} active{% endif %}">
                            <a href="{% url "prints:by_name" %}" class="nav-link">Indeks nazwisk</a>
                        </li>
                        <!--<li class="nav-item{% if request.resolver_match.url_name == "contact" %} active{% endif %}">-->
                            <!--<a href="{% url "contact" %}" class="nav-link">Kontakt</a>-->
                        <!--</li>-->
                        {% if user.is_authenticated %}
                        <li class="nav-item{% if request.resolver_match.url_name == "add" %} active{% endif %}">
                            <a href="{% url "management:add" %}" class="nav-link">Dodaj druki</a>
                        </li>
                        <li class="nav-item user-info">
                            <span>({{ user.username }})<br /></span>
                            <a href="{% url "logout" %}">Wyloguj</a>
                        </li>
                        {% else %}
                        <li class="nav-item{% if request.resolver_match.url_name == "login" %} active{% endif %}">
                            <a href="{% url "login" %}" class="nav-link">Zaloguj się</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>
        <hr class="hidden-sm-down">
    </div>
</div>