base/urls.py
#!/usr/bin/python
# coding: utf-8

from django.conf.urls import url
from django.conf import settings
from django.contrib.auth.views import login, logout

from . import views

urlpatterns = [
    url(r'^$', views.home, name='index'),
    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'logout.html'}, name='logout'),

]

urlpatterns += [url(r'^{}/$'.format(name), views.static_site(file), name=name)
                for name, file in settings.STATIC_SITES.items()]

management/urls.py
#!/usr/bin/python
# coding: utf-8
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.manage, name='management'),
    url(r'^add/$', views.add, name='add'),
    url(r'^edit/(?P<id>\d+)/$', views.edit, name='edit'),
    url(r'^remove/(?P<id>\d+)/$', views.remove, name='remove'),
    url(r'^upload_title_page/(?P<id>\d+)/$', views.upload_title_page, name='upload_title_page')
]

old_prints/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from prints import views as prints

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('base.urls')),
    url(r'^prints/', include('prints.urls', namespace='prints')),
    url(r'^manage/', include('management.urls', namespace='management')),
    url(r'^api/v1/prints/(?P<page>\d+)/$', prints.filter, name='filter'),
    url(r'^api/v1/name_index/(?P<page>\d+)/$', prints.name_index, name='name_index'),
]

prints/urls.py
#!/usr/bin/python
# coding: utf-8


from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.search, name='search'),
    url(r'^collection/$', views.collection, name='collection'),
    url(r'^by_name/$', views.by_name, name='by_name'),
    url(r'^single/(?P<id>\d+)/$', views.single, name="single"),
    url(r'^view/(?P<id>\d+)/$', views.view, name="view"),
]

prints/models.py
import os

from django.contrib.auth.models import User
from django.db import models
from django.conf import settings


# Create your models here.


class OldPrint(models.Model):
    id = models.AutoField(primary_key=True)
    owner = models.ForeignKey(User, verbose_name='właściciel')
    title_page = models.ForeignKey('Scan', null=True, verbose_name='strona tytułowa')
    # author = models.CharField(max_length=2, blank=True)
    # lp = models.CharField(max_length=3, blank=True)
    title = models.CharField(max_length=1024, blank=True, verbose_name='tytuł')
    title_page_content = models.TextField(blank=True, verbose_name='zawartość strony tytułowej')
    title_variant = models.CharField(max_length=256, blank=True, verbose_name='wariant tytułu')
    # ???
    author_khw = models.CharField(max_length=64, blank=True, verbose_name='autor khw')
    # ???
    author_doc = models.CharField(max_length=64, blank=True, verbose_name='autor dokumentu')
    publication_place = models.CharField(max_length=32, blank=True, verbose_name='miejsce wydania')
    publisher_name = models.CharField(max_length=128, blank=True, verbose_name='wydawca')
    publication_date = models.DateField(null=True, blank=True, verbose_name='data wydania')
    printing_place = models.CharField(max_length=32, blank=True, verbose_name='miejsce wydruku')
    printing_house_name = models.CharField(max_length=128, blank=True, verbose_name='drukarnia')
    printing_date = models.DateField(null=True, blank=True, verbose_name='data wydruku')
    number_of_pages = models.IntegerField(verbose_name='ilość stron')
    designation_illustration = models.CharField(max_length=32, blank=True, verbose_name='oznaczenia ilustracji')
    bibliography_format = models.CharField(max_length=32, blank=True, verbose_name='format bibliografii')
    # ???
    ownership_entries = models.CharField(max_length=512, blank=True, verbose_name='wpisy własnościowe')
    figerprint = models.CharField(max_length=64, blank=True, verbose_name='fingerprint')
    other_information = models.TextField(blank=True, verbose_name='inne informacje')
    co_founder = models.CharField(max_length=128, blank=True, verbose_name='współtwórca')
    keywords = models.CharField(max_length=256, blank=True, verbose_name='słowa kluczowe')
    source_type = models.CharField(max_length=128, blank=True, verbose_name='typ źródła')
    resource_identifier = models.CharField(max_length=16, blank=True, verbose_name='identyfikator zasobu')
    e_format = models.CharField(max_length=16, blank=True, verbose_name='elektroniczny format')
    source = models.CharField(max_length=512, blank=True, verbose_name='źródło')
    language_code = models.CharField(max_length=16, blank=True, verbose_name='kod języka')
    language = models.CharField(max_length=32, blank=True, verbose_name='język')
    bookbinding_block = models.CharField(max_length=16, blank=True, verbose_name='blok introligatorski')
    signature = models.CharField(max_length=16, blank=True, verbose_name='sygnatura')
    laws = models.CharField(max_length=16, blank=True, verbose_name='prawa')
    # ???
    daten_from = models.DateField(null=True, blank=True, verbose_name='datan od')
    daten_to = models.DateField(null=True, blank=True, verbose_name='datan do')

    @property
    def path(self):
        if settings.DEBUG:
            path = os.path.join(settings.BASE_DIR, 'prints', 'static')
        else:
            path = settings.STATIC_ROOT
        return os.path.join(path, 'img', 'data', str(self.id))

    @property
    def static(self):
        return '/'.join(['img', 'data', str(self.id)])

    @property
    def title_page_or_default(self):
        return self.title_page.static if self.title_page else settings.DEFAULT_TITLE_PAGE

    @property
    def dict(self):
        return {
            "id": self.id,
            "title_page": self.title_page_or_default,
            "title": self.title,
            "title_page_content": self.title_page_content,
            "title_variant": self.title_variant,
            "author_khw": self.author_khw,
            "author_doc": self.author_doc,
            "publication_place": self.publication_place,
            "publisher_name": self.publisher_name,
            "publication_date": self.publication_date,
            "printing_place": self.printing_place,
            "printing_house_name": self.printing_house_name,
            "printing_date": self.printing_date,
            "number_of_pages": self.number_of_pages,
            "designation_illustration": self.designation_illustration,
            "bibliography_format": self.bibliography_format,
            "ownership_entries": self.ownership_entries,
            "figerprint": self.figerprint,
            "other_information": self.other_information,
            "co_founder": self.co_founder,
            "keywords": self.key_words,
            "source_type": self.source_type,
            "resource_identifier": self.resource_identifier,
            "e_format": self.e_format,
            "source": self.source,
            "language_code": self.language_code,
            "language": self.language,
            "bookbinding_block": self.bookbinding_block,
            "signature": self.signature,
            "laws": self.laws,
            "daten_from": self.daten_from,
            "daten_to": self.daten_to,
        }

    @property
    def smart_dict(self):
        return {
            "id": self.id,
            "title_page": self.title_page.static if self.title_page else settings.DEFAULT_TITLE_PAGE,
            "title": self.title,
            # "title_page_content": self.title_page_content,
            "author_khw": self.author_khw,
            "publication_date": self.publication_date if self.publication_date else 'nieznana',
        }

    @property
    def key_words(self):
        return self.keywords.split(' ')


class Scan(models.Model):
    id = models.AutoField(primary_key=True)
    old_print = models.ForeignKey('OldPrint')
    page_number = models.IntegerField()
    format = models.CharField(max_length=8)
    # height = models.IntegerField()
    # width = models.IntegerField()

    @property
    def file_name(self):
        return '.'.join([str(self.page_number), self.format])

    @property
    def static(self):
        return '/'.join([self.old_print.static, str(self.file_name)])

    @property
    def path(self):
        return os.path.join(self.old_print.path, str(self.file_name))

    @property
    def thumbnail(self):
        return ''

prints/views.py
import json
import random

from django.conf import settings
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from prints.filters import PrintsFilter
from prints.models import OldPrint

LETTERS = [chr(i) for i in range(65, 91)]


def search(request):
    return render(request, "search.html")


def filter(request, page=1):
    filter = PrintsFilter(request.GET)
    paginator = Paginator(filter.qs.order_by('title'), settings.PRINTS_PER_PAGE)

    prints = [old_print.smart_dict for old_print in paginator.page(page)]
    return HttpResponse(json.dumps({'num_pages': paginator.num_pages, 'job': int(request.GET['job']), 'data': prints}))


def name_index(request, page=1):
    objects = OldPrint.objects.filter(author_khw__startswith=request.GET.get('letter', ''))
    paginator = Paginator(objects.order_by('title'), settings.PRINTS_PER_PAGE)

    prints = [old_print.smart_dict for old_print in paginator.page(page)]
    return HttpResponse(json.dumps({'num_pages': paginator.num_pages, 'job': int(request.GET['job']), 'data': prints}))


def collection(request):
    filter = PrintsFilter(request.GET)
    return render(request, "collection.html", {'default_title_page': settings.DEFAULT_TITLE_PAGE,
                                               'filter': filter})


def by_name(request):
    return render(request, "by_name.html", {'letters': LETTERS})


def single(request, id):
    return render(request, "single.html", {'print': get_object_or_404(OldPrint, id=id),
                                           'default_title_page': settings.DEFAULT_TITLE_PAGE})


def view(request, id):
    old_print = get_object_or_404(OldPrint, id=id)
    scans = old_print.scan_set.all()
    return render(request, "scan_set.html", {'default_title_page': settings.DEFAULT_TITLE_PAGE,
                                             'print': old_print,
                                             'scans': scans})

prints/templates/by_name.html
{% extends "base.html" %}{% load static %}
{% block title %}indeks nazwisk - starodruki{% endblock %}

<button type="button" data-filter="all">Show all</button>


{% block content %}
<div class="row">
    <div class="col index-letters controls">
        {% for letter in letters %}
            <button type="button" class="link brown-text index-letter control" onclick="javascript:get_prints('{{ letter }}')">{{ letter }}</button>
            <span class="print-info index-letter">  /  </span>
        {% endfor %}
    </div>
</div>
<div class="row mix-container">
    {% for letter, print in prints.items %}
    {% for path in print %}

    {% endfor %}
    {% endfor %}
</div>

{% endblock %}

{% block extra_script %}
<script src="{% static "/js/mixitup.min.js" %}"></script>

<script>

var current_page = 1;
var current_job = 0;

var mixer = mixitup('.mix-container', {
    controls: {
        toggleDefault: 'none'
    },
    data: {
        uidKey: 'id'
    },
    render: {
        target: render
    },
    selectors: {
        target: '[data-ref="mix"]'
    }
});

function try_set(data) {
    if (data.job != current_job) return;
    if (mixer.isMixing()){
        setTimeout(function (){try_set(data)}, 200);
        return;
    }
    if (data.job == current_job){
        mixer.dataset(data.data);
    }
}

function get_prints(letter) {
    current_job = (current_job + 1) % 65535;
    $.get('/api/v1/name_index/' + current_page.toString() + '/?letter=' + letter + '&job=' + current_job.toString(), function(data) {
        try_set($.parseJSON(data));
    });
}

function render(print) {
    return `
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-2" data-ref="mix", >
    <div class="content-box">
        <img src="{% static "" %}${print.title_page}" alt="Strona tytułowa" class="margin-b-20 img-fluid fixed-img">
        <h4 class="margin-b-0 brown-text" title="${print.title}">${print.title}</h4>
        <p class="margin-b-0 print-info" title="${print.author_khw}">${print.author_khw}</p>
        <p class="margin-b-20 print-info" title="${print.publication_date}"><i>(${print.publication_date})</i></p>
        <a href="/prints/single/${print.id}" class="brown-btn text-uppercase">Zobacz</a>
        <hr>
    </div>
</div>
`;};

$("#filter-form input").bind('input', function() {
    current_page = 1;
    get_prints('');
});

$(document).ready(function(){get_prints('')});

</script>

{% endblock %}

prints/templates/collection.html
{% extends "base.html" %}{% load static %}
{% block title %}przeglądaj - starodruki{% endblock %}


{% block content %}
<div class="margin-t-small"></div>
<div class="row">
    <div class="col-md-3 col-sm-4 col-lg-2">
        <form id="filter-form" class="filter-form">
            <h5 class="brown-text t-title">Filtrowanie</h5>

            {{ filter.form.as_p }}

            <!--<button type="submit">Filtruj</button>-->
        </form>
    </div>
    <div class="col-md-9 col-sm-8 col-lg-10">
        <div class="row mix-container"></div>
        <div class="row text-center">
            <div class="pages" role="group">
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block extra_script %}
<script src="{% static "/js/mixitup.min.js" %}"></script>

<script>

var current_page = 1;
var current_job = 0;
var num_pages = 1;

var mixer = mixitup('.mix-container', {
    controls: {
        toggleDefault: 'none'
    },
    data: {
        uidKey: 'id'
    },
    render: {
        target: render
    },
    selectors: {
        target: '[data-ref="mix"]'
    }
});

function update_pages() {
    text = '';
    k = current_page - 2;
    if (k<1) {k=1;};
    if (current_page > 1) {
        text = '<button onclick="javascript:previous_page()" class="btn brown-btn page-arrow"><<</button>';
    }

    for (;k <= current_page+2 && k <= num_pages; k++){
        if (k == current_page){
            text = text + '<button class="btn brown-btn page-number active">' + k + '</button>';
        }
        else {
            text = text + '<button onclick="javascript:page('+k+')" class="btn brown-btn page-number">' + k + '</button>';
        }
    }

    if (num_pages > current_page) {
        text = text + '<button onclick="javascript:next_page()" class="btn brown-btn page-arrow">>></button>';
    }
    $('.pages').html(text);
}

function try_set(data) {
    if (data.job != current_job) return;
    if (mixer.isMixing()){
        setTimeout(function (){try_set(data)}, 200);
        return;
    }
    if (data.job == current_job){
        num_pages = data.num_pages;
        mixer.dataset(data.data);
        update_pages();
    }
}

function get_prints() {
    current_job = (current_job + 1) % 65535;
    $.get('/api/v1/prints/' + current_page.toString() + '/?' + $('#filter-form').serialize() + '&job=' + current_job.toString(), function(data) {
        try_set($.parseJSON(data));
    });
}

function render(print) {
    return `
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-3" data-ref="mix", >
    <div class="content-box">
        <img src="{% static "" %}${print.title_page}" alt="Strona tytułowa" class="margin-b-20 img-fluid fixed-img">
        <h4 class="margin-b-0 brown-text" title="${print.title}">${print.title}</h4>
        <p class="margin-b-0 print-info" title="${print.author_khw}">${print.author_khw}</p>
        <p class="margin-b-20 print-info" title="${print.publication_date}"><i>(${print.publication_date})</i></p>
        <a href="/prints/single/${print.id}" class="brown-btn text-uppercase">Zobacz</a>
        <hr>
    </div>
</div>
`;};

$("#filter-form input").bind('input', function() {
    current_page = 1;
    get_prints();
});

$(document).ready(get_prints);

function page(page){
    if (page > 0 && page <= num_pages){
        current_page = page;
        update_pages();
        get_prints();
    }
}

function next_page(){
    page(current_page+1);
};

function previous_page(){
    page(current_page-1);
};



</script>

{% endblock %}

prints/templates/filter_prints.html
{% extends "base.html" %}{% load static %}
{% block title %}przeglądaj - starodruki{% endblock %}


{% block content %}
<div class="margin-t-small"></div>
<div class="row mix-container">
    {% include "print_set.html" %}
</div>

{% endblock %}

{% block script %}
{{ block.super }}
<script src="{% static "/js/mixitup.min.js" %}"></script>

<script>

    function render(print) {
        return `
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-2" data-ref="mix", >
    <div class="content-box">
        <img src="{% static "" %}${print.title_page}" alt="Strona tytułowa" class="margin-b-20 img-fluid fixed-img">
        <h4 class="margin-b-20 brown-text">${print.title}</h4>
        <p class="margin-b-20 print-info">${print.title_page_content}</p>
        <a href="{% url "prints:single" 0 %}" class="brown-btn text-uppercase">Zobacz</a>
        <hr>
    </div>
</div>
`;
    };

    var mixer = mixitup('.mix-container', {
        controls: {
            toggleDefault: 'none'
        },
        data: {
            uidKey: 'id'
        },
        render: {
            target: render
        },
        selectors: {
            target: '[data-ref="mix"]'
        }
    });
    mixer.dataset({{ prints|safe }})
</script>

{% endblock %}

prints/templates/form.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <form class="old-print-edit" method="POST" action="">
            <h2 class="brown-text t-title">{{ title }}</h2>
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">Zapisz</button>
        </form>
    </div>
</div>
{% endblock %}

prints/templates/photo_swipe_container.html
    <div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">

        <div class="pswp__bg"></div>

        <div class="pswp__scroll-wrap">

            <div class="pswp__container">
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
            </div>

            <div class="pswp__ui pswp__ui--hidden">

                <div class="pswp__top-bar">

                    <div class="pswp__counter"></div>

                    <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>

                    <button class="pswp__button pswp__button--share" title="Share"></button>

                    <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>

                    <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>

                    <div class="pswp__preloader">
                        <div class="pswp__preloader__icn">
                          <div class="pswp__preloader__cut">
                            <div class="pswp__preloader__donut"></div>
                          </div>
                        </div>
                    </div>
                </div>

                <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                    <div class="pswp__share-tooltip"></div>
                </div>

                <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
                </button>

                <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
                </button>

                <div class="pswp__caption">
                    <div class="pswp__caption__center"></div>
                </div>

            </div>

        </div>

    </div>

prints/templates/scan_set.html
{% extends "base.html" %}{% load static %}
{% block title %}przeglądaj - starodruki{% endblock %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static "gallery/photoswipe.css" %}">
    <link rel="stylesheet" href="{% static "gallery/default-skin/default-skin.css" %}">
{% endblock %}

{% block content %}
<div class="margin-t-small"></div>
<div class="row margin-b-20">
    <div class="col-md-6">
        <h3 class="brown-text print-title">{{ print.title }}</h3>
    </div>
    {% if user.is_authenticated %}
    <div class="col-md-6">
        <button onclick="removingMode()" class="brown-btn">Dodaj</button>
        <button onclick="removingMode()" class="brown-btn">Usuń zaznaczone</button>
    </div>
    {% endif %}
</div>
<div class="row">
    <div class="col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2">
        <div class="scan-box margin-b-15">
            <div class="thumbnail">
                <img onclick="javascript:showGallery(0);" src="https://farm4.staticflickr.com/3894/15008518202_b016d7d289_m.jpg" alt="" />
            </div>
            {% if user.is_authenticated %}
            <input type="checkbox" id="test1" />
            {% endif %}
            <!--<label></label>-->
            <span>1</span>
        </div>
    </div>
    <div class="col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2">
        <div class="scan-box margin-b-15">
            <div class="thumbnail">
                <img onclick="javascript:showGallery(1);" src="https://farm6.staticflickr.com/5591/15008867125_68a8ed88cc_m.jpg" alt="" />
            </div>
            <input type="checkbox" id="test1" />
            <!--<label></label>-->
            <span>2</span>
        </div>
    </div>
</div>

{% include "photo_swipe_container.html" %}
{% endblock %}

{% block extra_script %}
    <script src="{% static "gallery/photoswipe.min.js" %}"></script>
    <script src="{% static "gallery/photoswipe-ui-default.min.js" %}"></script>

    <script type="text/javascript">
    var pswpElement = document.querySelectorAll('.pswp')[0];
    var items = [
        {
            src: 'https://farm4.staticflickr.com/3894/15008518202_c265dfa55f_h.jpg',
            w: 1600,
            h: 1600
        },
        {
            src: 'https://farm6.staticflickr.com/5591/15008867125_b61960af01_h.jpg',
            w: 1600,
            h: 1068
        }
    ];

showGallery = function(current_index){
    var gallery = new PhotoSwipe( pswpElement, PhotoSwipeUI_Default, items, {index: current_index});
    gallery.init();
}

    </script>
{% endblock %}

prints/templates/search.html
{% extends "base.html" %}
{% block title %}info - starodruki{% endblock %}


{% block content %}
<div class="row search-section">
    <!--<div class="col-lg-2 col-md-1"></div>-->
    <div class="col">
        <form action="{% url "prints:collection" %}" method="get" class="search">
                <input type="text" id="search" name="title__contains" placeholder="Szukaj"/>
                <button type="submit">Szukaj</button>
        </form>
    </div>
    <!--<div class="col-lg-2 col-md-1"></div>-->
</div>

{% endblock %}

prints/templates/single.html
{% extends "base.html" %}{% load static %}

{% block title %}{{ print.title }}{% endblock %}

{% block content %}
<div class="row">
    <h3 class="brown-text print-title margin-b-20">{{ print.title }}</h3>
    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-6 col-xl-6">
        <div class="row margin-b-30 text-center" id="title-img-container">
            {% if print.title_page %}
            <img src="{% static print.title_page.static %}" alt="Strona tytułowa" class="title-img">
            {% if user.is_authenticated %}
            <span onclick="javascript:show_dropzone()" class="change-title">Zmień stronę tytułową</span>
            {% endif %}
            {% else %}
            {% if user.is_authenticated %}
            <span onclick="javascript:show_dropzone()" class="default-title-page" style="background-image: url({% static "img/add.png" %})">
                <img src="{% static default_title_page %}" alt="(Brak strony tytułowej)" class="title-img" />
            </span>
            {% else %}
                <img src="{% static default_title_page %}" alt="(Brak strony tytułowej)" class="title-img" />
            {% endif %}
            {% endif %}
        </div>
        <hr />
        <div class="row">
            <p class="title-page">{% if print.title_page_content %}{{ print.title_page_content }}{% else %}<i>(brak)</i>{% endif %}</p>
        </div>
    </div>
    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-6 col-xl-6 padding-r-30">
        <div class="row">
            <ul class="keywords">
                {% for keyword in print.key_words %}
                    <li class="keyword">
                        <a href="{% url "prints:collection" %}?keywords__contains={{ keyword }}" class="keyword">{{ keyword }}</a>
                    </li>
                {% endfor %}
            </ul>

            <ul class="print-info">
                <li class="info-item">
                    <div class="info-label">Tytuł:</div>
                    <div class="info-data">{{ print.title }}</div>
                </li>
                <li class="info-item">
                    <div class="info-label">Autor:</div>
                    <div class="info-data">{{ print.author }}</div>
                </li>
                <li class="info-item">
                    <div class="info-label">Data wydania:</div>
                    <div class="info-data">{{ print.date }}</div>
                </li>
                <li class="info-item">
                    <div class="info-label">Miejsce wydania:</div>
                    <div class="info-data">{{ print.place }}</div>
                </li>
                <li class="info-item">
                    <div class="info-label">Wydawca:</div><div class="info-data">{{ print.publisher }}</div>
                </li>
                <li class="info-item">
                    <div class="info-label">Sygnatura:</div>
                    <div class="info-data">{{ print.signature }}</div>
                </li>
            </ul>
            <div class="button-box">
                <a href="{% url "prints:view" print.id %}" class="brown-btn">Zobacz całość</a>
                {% if user.is_authenticated %}
                <a href="{% url "management:edit" print.id %}" class="brown-btn margin-l-15">Edytuj informacje</a>
                {% endif %}
            </div>
        </div>

        <div class="row">
            <ul class="share">
                <li class="share">
                    <a href="http://www.facebook.com/share.php?u={{ request.build_absolute_uri }}" class="fa fa-facebook share"></a>
                </li>
                <li class="share">
                    <a href="https://twitter.com/intent/tweet?button_hashtag=TwitterStories" class="fa fa-twitter share"></a>
                </li>
                <!--<li class="share">-->
                    <!--<a href="" class="fa fa-google-plus share"></a>-->
                <!--</li>-->
                <li class="share">
                    <a href="mailto:?body={{ request.build_absolute_uri }}" class="fa fa-envelope share"></a>
                </li>
            </ul>
        </div>
    </div>
</div>
{% if user.is_authenticated %}
<div class="overlay-page" id="drop-title-page">
    <div id="title-page-dropzone" class="dropzone-box">
        <div onclick="$('#drop-title-page').hide();" class="close-btn"></div>
        <div class="dropzone-text">
            Przeciągnij i upuść zdjęcie, albo kliknij i wyszukaj...
        </div>
    </div>
</div>
{% endif %}
{% endblock %}


{% block extra_script %}
{% if user.is_authenticated %}
<script src="{% static "js/dropzone.js" %}"></script>
<script>


var title_box_content = '<img src="{% static "" %}{path}?{timestamp}" alt="Strona tytułowa" class="title-img"><span onclick="javascript:show_dropzone()" class="change-title">Zmień stronę tytułową</span>';

var titlePageDropzone = new Dropzone('#title-page-dropzone', {
    maxFilesize: 100, // MB
    maxFiles: 1,

    url: "{% url "management:upload_title_page" print.id %}",
    success: function(e, response){
        $('#drop-title-page').hide();
        $('#title-img-container').html(title_box_content.replace('{path}', response).replace('{timestamp}', new Date().getTime()));
    },
    error: function(e, err_msg, response){
        $('#drop-title-page').hide();
        alert('wystąpił błąd podczas ładowania, odśwież stronę i spróbuj jeszcze raz');
    },
    headers: {
        'X-CSRFToken': '{{ csrf_token }}'
    }
})


$('#drop-title-page').click(function(e){
    $('#drop-title-page').hide();
}).children().click(function(e) {return false;});

$(document).keyup(function(e) {
     if (e.keyCode == 27) {
        $('#drop-title-page').hide();
    }
});

show_dropzone = function(){
    titlePageDropzone.removeAllFiles();
    $('#drop-title-page').show();
};

</script>
{% endif %}
{% endblock %}